### ISSUE TITLE
average_max_speed_at_age gives NaN

### ISSUE THREAD

**Issue by DarkStar1997** [sayansil/Ecosystem#4] opened 2020-02-26 19:16 UTC

**Comment by sayansil** [comment] 2020-02-26 19:18
Please provide a description. If you're confused, we have provided a template for you.

**Comment by DarkStar1997** [comment] 2020-02-28 19:20
Resolved in https://github.com/sayansil/Ecosystem/commit/1662a9e249c3484aeddc2a4a4919891727573827

**Comment by sayansil** [comment] 2021-07-15 18:36
Duplicate of #22

**Closed as completed by sayansil** 2021-07-15 18:36 UTC
Labels: bug
